# Generated by Django 2.2 on 2020-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebase',
            name='file',
            field=models.FileField(upload_to='file_base', verbose_name='Фаил'),
        ),
    ]
