# Generated by Django 2.2 on 2020-03-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200314_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filebase',
            old_name='name_file',
            new_name='name',
        ),
    ]
